### ISSUE TITLE
Shards 0.6.2 doesn't compile on OTP 23.0.3 on OS X 10.15

### ISSUE THREAD

**Issue by errnaa** [cabol/shards#48] opened 2020-08-30 17:20 UTC
Compiling src/shards_dist.erl failed
src/shards_dist.erl:125: pg2:join/2 is deprecated and will be removed in OTP 24; use use 'pg' instead
src/shards_dist.erl:130: pg2:get_members/1 is deprecated and will be removed in OTP 24; use use 'pg' instead
src/shards_dist.erl:135: pg2:leave/2 is deprecated and will be removed in OTP 24; use use 'pg' instead
src/shards_dist.erl:145: pg2:get_members/1 is deprecated and will be removed in OTP 24; use use 'pg' instead
src/shards_dist.erl:440: pg2:delete/1 is deprecated and will be removed in OTP 24; use use 'pg' instead
src/shards_dist.erl:441: pg2:create/1 is deprecated and will be removed in OTP 24; use use 'pg' instead

** (Mix) Could not compile dependency :shards, "/Users/.../.mix/rebar3 bare compile --paths="/Users/.../Projects/.../_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile shards", update it with "mix deps.update shards" or clean it with "mix deps.clean shards"

Happened directly after upgrading OTP. Reinstalled erlang and elixir once afterwards. Unsure why it is failing due to depreciations.

Probably same issue as: https://github.com/cabol/shards/issues/40#issuecomment-666756227

**Comment by hmatinho** [comment] 2020-09-02 14:30
i would say it's more inline with issue #47 when that gets implemented this should solve as well

**Comment by cabol** [comment] 2020-10-12 13:02
There are several and new breaking changes in the master branch already (it should fix this issue). In short, `shards` was completely refactored, with a new and much better design, several improvements, etc., but they will be available since `v1.0.0`. Frum user/client standpoint there are no changes because `shards` in the end implement the same ETS API and that won't change. But, [shards_dist](https://github.com/cabol/shards_dist) was removed and the plan is to create a separate project for it, the issue is for the moment is not supported, since it has to be re-implement it according to the new architecture; hopefully soon 🤞 .

**Comment by cabol** [comment] 2020-10-28 10:19
I'll close this issue since it doesn't apply anymore, with `shards` v1 the distributed module `shards_dist` will be in a separate repo, so by the time there is a first implementation ready, there will be support for `pg` and `pg2` (for OTP < 23).

**Closed as completed by cabol** 2020-10-28 10:19 UTC
