### ISSUE TITLE
Compilation error with OTP 26

### ISSUE THREAD

**Issue by mrz** [cabol/shards#63] opened 2024-05-24 13:16 UTC
When compiling using OTP 26 and rebar 3.22.0 we get the following error:

```
❯ rebar3 compile +debug_info
===> Fetching rebar3_proper v0.12.1
===> Analyzing applications...
===> Compiling rebar3_proper
===> Fetching rebar3_ex_doc v0.2.23
===> Analyzing applications...
===> Compiling rebar3_ex_doc
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling shards
===> Compiling src/shards.erl failed
src/shards.erl:1505:23: type variable 'Pos' is only used once (is unbound)
src/shards.erl:1505:28: type variable 'Value' is only used once (is unbound)
```

These are the detailed rebar and OTP versions:

```
❯ rebar3 --version
rebar 3.22.0 on Erlang/OTP 26 Erts 14.1.1
❯ erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
26.1.2
```

We believe this to be related to this change introduced in `OTP` 26: https://www.erlang.org/patches/otp-26.0#OTP-18389

**Comment by cabol** [comment] 2024-05-24 13:44
Thanks for spotting this issue, will take a look as soon as possible.

**Comment by cabol** [comment] 2024-05-25 10:37
I think this issue should be fixed by https://github.com/cabol/shards/pull/61. I'll release a version bump.

**Comment by cabol** [comment] 2024-05-25 11:22
I have published a new release `1.1.1`. Please try it out and let me know if the issue is fixed. Thanks!

**Closed as completed** 2024-05-25 11:25 UTC

**Comment by Zhukikov** [comment] 2024-05-29 17:13
I checked and my build works without any issues. Thank you for a quick release!

**Comment by mrz** [comment] 2024-06-04 13:03
Thanks @cabol!
